-- Combined SQL Scripts
-- Generated by executing all SQL files in database-plans folder
-- Run this script in your Supabase SQL Editor

-- =====================================================
-- TABLE CREATION AND SCHEMA SETUP
-- =====================================================

-- From: 01-create-tables.sql
-- Create users table
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'cashier' CHECK (role IN ('admin', 'manager', 'cashier', 'chef')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create restaurants table
CREATE TABLE IF NOT EXISTS restaurants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  address TEXT,
  phone TEXT,
  email TEXT,
  owner_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create menus table
CREATE TABLE IF NOT EXISTS menus (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create menu_items table
CREATE TABLE IF NOT EXISTS menu_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  menu_id UUID NOT NULL REFERENCES menus(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  category TEXT,
  availability BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create orders table
CREATE TABLE IF NOT EXISTS orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  customer_name TEXT,
  table_number TEXT,
  total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'preparing', 'ready', 'completed', 'cancelled')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create order_items table
CREATE TABLE IF NOT EXISTS order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id UUID NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  price DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create reservations table
CREATE TABLE IF NOT EXISTS reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  customer_name TEXT NOT NULL,
  customer_phone TEXT,
  customer_email TEXT,
  party_size INTEGER NOT NULL CHECK (party_size > 0),
  reservation_date DATE NOT NULL,
  reservation_time TIME NOT NULL,
  status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'cancelled', 'completed')),
  special_requests TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS inventory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  quantity DECIMAL(10,2) NOT NULL CHECK (quantity >= 0),
  unit TEXT NOT NULL,
  minimum_quantity DECIMAL(10,2) DEFAULT 0 CHECK (minimum_quantity >= 0),
  category TEXT,
  supplier TEXT,
  last_restocked DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create restaurant_settings table
CREATE TABLE IF NOT EXISTS restaurant_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  setting_key TEXT NOT NULL,
  setting_value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(restaurant_id, setting_key)
);

-- =====================================================
-- INDEXES FOR PERFORMANCE
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_restaurants_owner_id ON restaurants(owner_id);
CREATE INDEX IF NOT EXISTS idx_menus_restaurant_id ON menus(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_menu_id ON menu_items(menu_id);
CREATE INDEX IF NOT EXISTS idx_menu_items_category ON menu_items(category);
CREATE INDEX IF NOT EXISTS idx_orders_restaurant_id ON orders(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_menu_item_id ON order_items(menu_item_id);
CREATE INDEX IF NOT EXISTS idx_reservations_restaurant_id ON reservations(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_reservations_date ON reservations(reservation_date);
CREATE INDEX IF NOT EXISTS idx_reservations_status ON reservations(status);
CREATE INDEX IF NOT EXISTS idx_inventory_restaurant_id ON inventory(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_category ON inventory(category);
CREATE INDEX IF NOT EXISTS idx_restaurant_settings_restaurant_id ON restaurant_settings(restaurant_id);

-- =====================================================
-- TRIGGERS FOR UPDATED_AT
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_restaurants_updated_at BEFORE UPDATE ON restaurants FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_menus_updated_at BEFORE UPDATE ON menus FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_menu_items_updated_at BEFORE UPDATE ON menu_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_orders_updated_at BEFORE UPDATE ON orders FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_reservations_updated_at BEFORE UPDATE ON reservations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_inventory_updated_at BEFORE UPDATE ON inventory FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_restaurant_settings_updated_at BEFORE UPDATE ON restaurant_settings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- ADDITIONAL COLUMNS AND FEATURES
-- =====================================================

-- From: add-category-column.sql
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'main';

-- From: add-chef-role.sql
ALTER TABLE users ADD CONSTRAINT IF NOT EXISTS users_role_check CHECK (role IN ('admin', 'manager', 'cashier', 'chef'));

-- From: add-comprehensive-roles.sql
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('admin', 'manager', 'cashier', 'chef', 'waiter', 'host'));

-- =====================================================
-- RESTAURANT SETTINGS TABLE
-- =====================================================

-- From: create-restaurant-settings-table.sql
CREATE TABLE IF NOT EXISTS restaurant_settings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  setting_key TEXT NOT NULL,
  setting_value TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(restaurant_id, setting_key)
);

-- =====================================================
-- USER CONTEXT FUNCTION
-- =====================================================

-- From: create-user-context-function.sql
CREATE OR REPLACE FUNCTION get_user_context(user_email TEXT)
RETURNS TABLE (
  user_id UUID,
  user_name TEXT,
  user_role TEXT,
  restaurant_id UUID,
  restaurant_name TEXT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        u.id as user_id,
        u.name as user_name,
        u.role as user_role,
        r.id as restaurant_id,
        r.name as restaurant_name
    FROM users u
    LEFT JOIN restaurants r ON u.id = r.owner_id
    WHERE u.email = user_email;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- DELETE RESTAURANT PROCEDURE
-- =====================================================

-- From: delete-restaurant-procedure.sql
CREATE OR REPLACE FUNCTION delete_restaurant(restaurant_uuid UUID)
RETURNS BOOLEAN AS $$
DECLARE
    restaurant_exists BOOLEAN;
BEGIN
    -- Check if restaurant exists
    SELECT EXISTS(SELECT 1 FROM restaurants WHERE id = restaurant_uuid) INTO restaurant_exists;
    
    IF NOT restaurant_exists THEN
        RAISE EXCEPTION 'Restaurant with ID % does not exist', restaurant_uuid;
    END IF;
    
    -- Delete the restaurant (cascade will handle related records)
    DELETE FROM restaurants WHERE id = restaurant_uuid;
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================
-- ENHANCED CASCADE DELETE
-- =====================================================

-- From: enhance-cascade-delete.sql
-- Add cascade delete for all related tables
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_restaurant_id_fkey;
ALTER TABLE orders ADD CONSTRAINT orders_restaurant_id_fkey 
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;

ALTER TABLE menus DROP CONSTRAINT IF EXISTS menus_restaurant_id_fkey;
ALTER TABLE menus ADD CONSTRAINT menus_restaurant_id_fkey 
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;

ALTER TABLE reservations DROP CONSTRAINT IF EXISTS reservations_restaurant_id_fkey;
ALTER TABLE reservations ADD CONSTRAINT reservations_restaurant_id_fkey 
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;

ALTER TABLE inventory DROP CONSTRAINT IF EXISTS inventory_restaurant_id_fkey;
ALTER TABLE inventory ADD CONSTRAINT inventory_restaurant_id_fkey 
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;

ALTER TABLE restaurant_settings DROP CONSTRAINT IF EXISTS restaurant_settings_restaurant_id_fkey;
ALTER TABLE restaurant_settings ADD CONSTRAINT restaurant_settings_restaurant_id_fkey 
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id) ON DELETE CASCADE;

-- =====================================================
-- ROLES AND ACCESS PERMISSIONS
-- =====================================================

-- From: roles-access-permissions.sql
-- Create roles table for better permission management
CREATE TABLE IF NOT EXISTS roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    permissions JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert default roles
INSERT INTO roles (name, description, permissions) VALUES
    ('admin', 'Full system access', '{"all": true}'),
    ('manager', 'Restaurant management access', '{"restaurants": ["read", "write"], "menus": ["read", "write"], "orders": ["read", "write"], "inventory": ["read", "write"]}'),
    ('cashier', 'Point of sale access', '{"orders": ["read", "write"], "menus": ["read"]}'),
    ('chef', 'Kitchen access', '{"orders": ["read"], "menus": ["read"]}'),
    ('waiter', 'Service staff access', '{"orders": ["read", "write"], "menus": ["read"], "reservations": ["read", "write"]}'),
    ('host', 'Host access', '{"reservations": ["read", "write"], "menus": ["read"]}')
ON CONFLICT (name) DO NOTHING;

-- =====================================================
-- SAMPLE DATA
-- =====================================================

-- From: add-sample-data.sql
-- Create sample admin user (password: admin123)
INSERT INTO users (email, password_hash, name, role) VALUES
('admin@restaurant.com', '$2b$10$rOzJqQjQjQjQjQjQjQjQjOzJqQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQjQ', 'System Admin', 'admin')
ON CONFLICT (email) DO NOTHING;

-- Create sample restaurant
INSERT INTO restaurants (name, address, phone, email, owner_id) VALUES
('Sample Restaurant', '123 Main St, City, State 12345', '+1-555-0123', 'info@samplerestaurant.com', 
    (SELECT id FROM users WHERE email = 'admin@restaurant.com' LIMIT 1))
ON CONFLICT DO NOTHING;

-- =====================================================
-- CLEANUP AND FINAL SETUP
-- =====================================================

-- From: clean-setup.sql
-- Clean any duplicate data
DELETE FROM order_items WHERE order_id NOT IN (SELECT id FROM orders);
DELETE FROM menu_items WHERE menu_id NOT IN (SELECT id FROM menus);

-- From: final-setup.sql
-- Enable Row Level Security
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE menus ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE restaurant_settings ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- From: verify-tables.sql
-- Verify all tables were created successfully
SELECT 'users' as table_name, COUNT(*) as record_count FROM users
UNION ALL
SELECT 'restaurants' as table_name, COUNT(*) as record_count FROM restaurants
UNION ALL
SELECT 'menus' as table_name, COUNT(*) as record_count FROM menus
UNION ALL
SELECT 'menu_items' as table_name, COUNT(*) as record_count FROM menu_items
UNION ALL
SELECT 'orders' as table_name, COUNT(*) as record_count FROM orders
UNION ALL
SELECT 'reservations' as table_name, COUNT(*) as record_count FROM reservations
UNION ALL
SELECT 'inventory' as table_name, COUNT(*) as record_count FROM inventory
UNION ALL
SELECT 'restaurant_settings' as table_name, COUNT(*) as record_count FROM restaurant_settings;

-- =====================================================
-- COMPLETION MESSAGE
-- =====================================================

SELECT 'Database setup completed successfully!' as status,
       (SELECT COUNT(*) FROM users) as user_count,
       (SELECT COUNT(*) FROM restaurants) as restaurant_count,
       (SELECT COUNT(*) FROM menus) as menu_count,
       (SELECT COUNT(*) FROM menu_items) as menu_item_count;
